name: Run crawler
on:
  schedule:
    - cron:  '*/20 * * * *'
jobs:
  runCrawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run crawler
        run: |
          python "data/crawlWorldData.py"
          python "data/crawlKoreaRegionalData.py"
          python "data/Hopkins_world_data_parser.py"
          python "data/crawlWorldCumulativeData.py"
      - name: Commit files
        run: |
          git config --local user.email "commit-bot@taeuk.me"
          git config --local user.name "LiveCoronaBot"
          git add data/worldData.js data/koreaRegionalData.js data/HopkinsCoronaWorldData.js data/worldCumulativeData.js
          git commit -m "Run crawler and update data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
